### ISSUE TITLE
Simple test in linux ✌

### ISSUE THREAD

**Issue by yezz123** [google/gfbuild-SPIRV-Tools#13]
Can we test  **google/gfbuild-SPIRV-Tools** on linux mint 18 Cinnamon (64-bit).

**Comment by paulthomson** [comment]
I'm afraid this repo only does nightly builds of SPIRV-Tools. Sometimes it will fail. Actual testing of SPIRV-Tools is done upstream: https://github.com/KhronosGroup/SPIRV-Tools

They already test Ubuntu with several different compilers.
